project:
  type: website
  output-dir: docs
website:
  title: "CEPE-Fundar"
  navbar:
    background: "#2E27F3"
    logo: " "
    left:
      - href: index.qmd
        text: "Nosotros"
      - href: encuesta.qmd
        text: "Investigaci√≥n"  
    right:
      - icon: github
        href: https://github.com/cepe-fundar
format:
  html:
    theme: 
      - cosmo
      - styles.css
    css: styles.css
    toc: false
    mainfont: "Inter"
    fontfamily: "Inter"



